<script>
  import BackToHomeLink from "../components/BackToHomeLink.svelte";
  import BrowserSupport from "../components/BrowserSupport.svelte";
  import MdnDoc from "../components/MdnDoc.svelte";
  import { APP_DESCRIPTION, APP_NAME, APP_URL } from "../constants";
  import Page from "../layouts/Page.svelte";

  const title = "accent-color";
</script>

<svelte:head>
  <meta name="description" content={APP_DESCRIPTION} />
  <meta property="og:title" content="{title} ･ {APP_NAME}" />
  <meta property="og:description" content={APP_DESCRIPTION} />
  <meta property="og:url" content="{APP_URL}{title}/" />
</svelte:head>

<Page {title} />
<h1>{title}</h1>
<section>
  <MdnDoc path="Web/CSS/accent-color" text={title}>
    the <code>accent-color</code> css property sets the accent color for user-interface
    controls generated by some elements.
  </MdnDoc>
</section>
<section>
  <fieldset class="example1">
    <legend>#1</legend>
    <div>
      <input type="checkbox" id="checkbox1-1" checked />
      <label for="checkbox1-1">checkbox1</label>
    </div>
    <div>
      <input type="radio" id="radio1-1" name="radio1" checked />
      <label for="radio1-1">radio1</label>
      <input type="radio" id="radio1-2" name="radio1" />
      <label for="radio1-2">radio2</label>
    </div>
    <div>
      <label for="range1-1">range1</label>
      <input
        type="range"
        id="range1-1"
        min={0}
        max={100}
        step={10}
        value={50}
      />
    </div>
    <div>
      <label for="progress1-1">progress1</label>
      <progress id="progress1-1" max={100} value={50}>50%</progress>
      <span>50%</span>
    </div>
  </fieldset>
  <fieldset class="example2">
    <legend>#2</legend>
    <div>
      <input type="checkbox" id="checkbox2-1" checked />
      <label for="checkbox2-1">checkbox1</label>
    </div>
    <div>
      <input type="radio" id="radio2-1" name="radio2" checked />
      <label for="radio2-1">radio1</label>
      <input type="radio" id="radio2-2" name="radio2" />
      <label for="radio2-2">radio2</label>
    </div>
    <div>
      <label for="range2-1">range1</label>
      <input
        type="range"
        id="range2-1"
        min={0}
        max={100}
        step={10}
        value={50}
      />
    </div>
    <div>
      <label for="progress2-1">progress1</label>
      <progress id="progress2-1" max={100} value={50}>50%</progress>
      <span>50%</span>
    </div>
  </fieldset>
</section>
<section>
  <BrowserSupport
    items={[
      {
        value: "accent-color",
        chrome: "93",
        firefox: "92",
        safari: "15.4",
      },
    ]}
  />
</section>
<BackToHomeLink />

<style>
  fieldset {
    margin-bottom: 2.5rem;
  }

  progress + span {
    color: #b2bcd0;
    margin-left: 0.25rem;
  }

  .example1 input,
  .example1 progress {
    accent-color: var(--blue-300);
  }
</style>
